### PR TITLE
Added Annotations on the console for Auth.md

### PR DESCRIPTION
**Pull request by dino-saurabh**
Added Annotations above examples to make the purpose of examples explicit.

### CODE REVIEW

**Comment by dino-saurabh** [comment]
@Akayeshmantha Please review 

screenshots after the changes were made !!

upload

**Review by Akayeshmantha — CHANGES_REQUESTED** [review]
I cant see the changes in the markdowns @LuGO0

**Comment by dino-saurabh** [comment]
> I cant see the changes in the markdowns @LuGO0

@Akayeshmantha the examples were added earlier But I missed on to the annotations which I have started adding now and this is the last section with examples already added but the annotations missing so I added them.

**Comment by Akayeshmantha** [comment]
got it thanks for the PR

**Review by Akayeshmantha — APPROVED** [review]

**Pull request merged**
