### PR TITLE
Documenting Patient resource patient subsection

### PR DESCRIPTION
**Pull request by dino-saurabh**
1. added examples 
2. corrected payloads

### CODE REVIEW

**Comment by dino-saurabh** [comment]
@Akayeshmantha please review

**Review by Akayeshmantha — CHANGES_REQUESTED** [review]
This doesn't look right. Please make sure to maintain the git history properly. It shows that you have deleted all the content and added new snippets can we revert back.

**Comment by dino-saurabh** [comment]
@Akayeshmantha I will fix the merge conflict and the git history I dont know how this happened !!

**Comment by dino-saurabh** [comment]
@Akayeshmantha closing this PR I messed up the merge conflicts making a new PR

**Pull request closed without merging**
