### PR TITLE
Added java examples for package systemInformation

### PR DESCRIPTION
**Pull request by dino-saurabh**
1. added the java  example for the only operation systemInformation supports getSystemInformation.

### CODE REVIEW

**Comment by dino-saurabh** [comment]
@Akayeshmantha please review, this PR

**Comment by HerbertYiga** [comment]
Does this have any ticket ID?

**Comment by dino-saurabh** [comment]
@HerbertYiga No it dosent have.

**Review by Akayeshmantha — APPROVED** [review]
Thanks

**Pull request merged**
