### PR TITLE
Column width UI issue fixed

### PR DESCRIPTION
**Pull request by UthpalaPitawela**

### CODE REVIEW

**Comment by UthpalaPitawela** [comment]
@Akayeshmantha Could you review this PR?

**Review by Akayeshmantha — CHANGES_REQUESTED** [review]
Hi @UthpalaPitawela  

Please make sure to follow the best practices while sending PR.

Make sure to attach an image before and after the change.

Do mention what you did on the description and for what purpose.

But the change looks good to me great work on catching up the issue here cheers

**Comment by UthpalaPitawela** [comment]
Thanks @Akayeshmantha  for the feedback. I'll update the PR

**Comment by UthpalaPitawela** [comment]
**Issue**: Some table columns displayed in the console
**Cause**: Some texts were not broken and they displayed in one line
**Solution**: Break the text so that it will display in multiple lines 

**Before the update**: 
image


**After the update**: 
image

**Comment by UthpalaPitawela** [comment]
@Akayeshmantha I have updated the PR. Could you look into this?

**Review by Akayeshmantha — APPROVED** [review]
Great work

**Pull request merged**
