### PR TITLE
Documenting Observation Resource

### PR DESCRIPTION
**Pull request by dino-saurabh**
1. Added Internal links. 
2. Added examples.
3. Added missing attributes.

### CODE REVIEW

**Comment by HerbertYiga** [comment]
hi @LuGO0   does this have any existing ticket id?

**Comment by dino-saurabh** [comment]
> hi @LuGO0 does this have any existing ticket id?

No @HerbertYiga I just add these PRs to the documentation trello board these have no tickets associated with them :)

**Comment by dino-saurabh** [comment]
@Akayeshmantha  please review !!

**Review by Akayeshmantha — APPROVED** [review]
LGTM

**Pull request merged**
