### PR TITLE
fixup build warning

### PR DESCRIPTION
**Pull request by dino-saurabh**
1. fixup build warning

### CODE REVIEW

**Comment by dino-saurabh** [comment]
@ayesh I think this issue has been closed in travis here https://github.com/travis-ci/travis-ci/issues/6833 but this fix doesn't work out for me!!

**Comment by HerbertYiga** [comment]
@LuGO0  Thanks for taking on this,we could also create a ticket for it to ease the tracking.

**Comment by dino-saurabh** [comment]
@HerbertYiga do we have a JIRA for this project !?

**Review by Akayeshmantha — CHANGES_REQUESTED** [review]
@LuGO0  build is failing is this the correct PR ?

**Comment by dino-saurabh** [comment]
@Akayeshmantha this PR removes the warning wdm polling changes but it fails the travis build thats why I made it draft I will try and fix this later

**Comment by Akayeshmantha** [comment]
maybe u can rebase with the master now and see.

**Comment by dino-saurabh** [comment]
@Akayeshmantha sure I will check

**Comment by dino-saurabh** [comment]
No @Akayeshmantha I tried again it still fails :(

**Pull request closed without merging**
