### PR TITLE
documenting concept resource concept-description section

### PR DESCRIPTION
**Pull request by dino-saurabh**
1. Added examples
2. Fixed curl examples

### CODE REVIEW

**Comment by dino-saurabh** [comment]
@ayesh this PR is up for review !!

**Comment by HerbertYiga** [comment]
Thanks @LuGO0  did we have any ticket id for this

**Comment by dino-saurabh** [comment]
> Thanks @LuGO0 did we have any ticket id for this

No @HerbertYiga

**Review by Akayeshmantha — APPROVED** [review]
LGTM

**Pull request merged**
